version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - azure-cli/login-with-user:
          azure-password: Iamronaldo@cr7 
          azure-username: sekhar.parida@thinkartha.com 

workflows:
  example-workflow:
    jobs:
      - example-job

